br = ("Santos","Sao Paulo","Chapecoense","Vasco","Bahia","Cruzeiro","Palmeiras","Botafogo","Fluminense","Goias")
print(f"TIMES: {br}")
print("-"*100)
print("CINCO PRIMEIROS: ",br[:5])
print("-"*100)
print("QUATRO ULTIMOS: ",br[6:])
print("-"*100)
print("ORDEDM ALFABETICA: ",sorted(br))
print("-"*100)
chape = 1+br.index("Chapecoense")
print(f"POSICAO DA CHAPECOENSE: {chape}")